apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd  # Argo CD 所在的 namespace
spec:
  project: default
  source:
    repoURL: https://github.com/markpeng-lab/test.git  # 你的 GitHub repo
    path: prometheus  # Helm YAML 和 values 文件所在的路徑
    targetRevision: HEAD
    helm:
      valueFiles:
        - prometheus.yaml  # 指向自定義的 values 文件
  destination:
    server: https://kubernetes.default.svc  # 指向 Kubernetes API
    namespace: mark  # 安裝 Prometheus 的 namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
