apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: mark  # 指定與 NGINX Deployment 相同的命名空間
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80           # 服務的端口
      targetPort: 80     # NGINX 容器內部的端口
  type: LoadBalancer      # 使用 LoadBalancer 以獲取外部 IP