apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: mark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql  # 指向 MySQL Service 名稱
        - name: WORDPRESS_DB_USER
          value: root  # MySQL 用戶名
        - name: WORDPRESS_DB_PASSWORD
          value: Sa0985297528  # MySQL 密碼
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        resources:  # 設定資源限制
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
